# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  schedule: 
    - cron: "0 12 * * *"
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch:

name: process_new_reports

jobs:
  process_new_reports:
    runs-on: ubuntu-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      ENV1: ${{ vars.RCLONE_CONFIG }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash        
      - name: Run sync
        shell: bash
        env:
          RCLONE_CONFIG: "${{ vars.RCLONE_CONFIG }}"
        run: |
          set -ex
          echo $RCLONE_CONFIG | base64 -d > rclone.conf
          rclone \
            --config rclone.conf \
            listremotes

      - name: create_reportdir
        run: mkdir -p report_dir

      - name: check_config
        run: cat rclone.conf
        
      - name: rclone_copy_last_mod_date
        run: 'rclone --config rclone.conf copy r2:bioconductor/checkResults/last_mod_date.csv report_dir/'

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, any::devtools, local::.
          needs: website

      - name: "install package"
        run: devtools::install('.', dependencies = TRUE)
        shell: Rscript {0}

      - name: "run workflow"
        run: |
          library(BiocBuildDB)
          dir.create('report_dir')
          process_all_new_reports('report_dir/last_mod_date.csv', 'report_dir')
          list.files('report_dir')
        shell: Rscript {0}
        
      - name: rclone_sync_results
        run: 'rclone --config rclone.conf copy report_dir/ r2:bioconductor/checkResults/'
